### ISSUE TITLE
Learn to use a build system

### ISSUE THREAD

**Issue by The-Epic** [ziuee/cPractice#6]
You really really need to learn to use a build system you are distributing spigot jars indirectly and you are most likely open to a dmca or copyright take down of the repo, using maven or gradle will heavily help you a lot

**Comment by ziuee** [comment]
Do you not realize we’re using maven? “You really need to learn to use a build system”, like what are you even saying, and the reasoning for having to add all the spigots are because devs now adays doesn’t know how to make api’s for their spigots. Though I can just remove those from the dependencies folder but that’s when everyone starts complaining about missing dependencies.

**Comment by ziuee** [comment]
Most of these spigots are public or open source anyways so it shouldn’t harm at all, nor is this a open source project I’ll be continuing on, but if I did in fact continue working on this then I’d have prevented using scopes by changing them to local instead.
